[general]
import = [
    "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

[colors]
transparent_background_colors = true

[cursor]
blink_interval = 150

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 11

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[window]
decorations = "none"
dynamic_title = true
opacity = 1
startup_mode = "Windowed"

[window.padding]
x = 8
y = 8
