[colors]
transparent_background_colors = true

[cursor]
blink_interval = 150

[cursor.style]
blinking = "Always"

[font]
size = 11

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Windowed"

[window.padding]
x = 16
y = 16
